# Uncomment the next line to define a global platform for your project
platform :ios, '10.0' # min version required by aware

target 'EEG101' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EEG101
  
  pod 'AWAREFramework', :git=>'https://github.com/nuKs/AWAREFramework-iOS.git', :branch => 'nuKs/encryption'

#  target 'EEG101Tests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
